name: JoinGuard
version: '${version}'
main: com.epicplayera10.joinguard.JoinGuard
api-version: '1.13'
authors: [EpicPlayerA10, Raelx]
permissions:
  joinguard.admin:
    description: Permission to use all JoinGuard commands
    default: op
  joinguard.notify.updatecheck:
    description: Permission to receive update notifications
    default: op
